inocan-group/vue3-google-map

src/components/GoogleMap.vue, src/shared/index.ts
=> feat: map events

package.json, src/components/GoogleMap.vue
Add options to support map localization.
Closes #7
=> Add map localization options

package.json, src/@types/index.ts, src/components/CustomControl.vue, src/components/GoogleMap.vue, src/composables/index.ts, src/composables/useMap.ts, src/composables/useSetupMapComponent.ts, src/shared/index.ts, yarn.lock
=> fix: multiple maps

src/components/CustomControl.vue, src/components/GoogleMap.vue, src/composables/useSetupMapComponent.ts
=> fix: separate map node from subcomponent nodes

src/components/GoogleMap.vue, src/shared/index.ts
=> fix: api loading

src/components/GoogleMap.vue
=> feat: api version

.eslintrc.js, .gitignore, docs/examples/ApiAccessExample.vue, package.json, src/@types/index.ts, src/components/Circle.ts, src/components/CustomControl.vue, src/components/GoogleMap.vue, src/components/Marker.ts, src/components/Polygon.ts, src/components/Polyline.ts, src/components/Rectangle.ts, src/composables/useSetupMapComponent.ts, src/shared/index.ts, src/themes/aubergine.ts, src/themes/dark.ts, src/themes/grey.ts, src/themes/minimal.ts, src/themes/retro.ts, src/themes/roadways.ts, src/themes/roadwaysMinimal.ts, src/themes/ultraLight.ts, tsconfig.json, yarn.lock
I plan to contribute to this library i use and maybe make infoWindows in the near future, meanwhile i did a small refactor.
=> Map component refactor

package.json, yarn.lock
=> fix: make js-api-loader a dependency

src/components/CustomControl.vue, src/components/GoogleMap.vue, src/components/InfoWindow.vue, src/components/index.ts, src/shared/index.ts
=> feat: info windows

package.json, src/components/CustomControl.vue, src/components/InfoWindow.vue, src/components/MarkerCluster.ts, src/components/index.ts, src/composables/useSetupMapComponent.ts, src/shared/index.ts, tsconfig.json, yarn.lock
=> feat: marker clusters

src/components/GoogleMap.vue
Hi, it would be great to add the mapId parameter in this component.
Thx !
=> Add mapId in GoogleMap Component

README.md, docs/.vitepress/config.js, docs/components/circle.md, docs/components/custom-control.md, docs/components/custom-marker.md, docs/components/info-window.md, docs/components/marker-cluster.md, docs/components/marker.md, docs/components/polygon.md, docs/components/polyline.md, docs/components/rectangle.md, package.json, src/components/CustomMarker.vue, src/components/GoogleMap.vue, src/components/InfoWindow.vue, src/components/Marker.ts, src/components/MarkerCluster.ts, src/components/index.ts, src/composables/useSetupMapComponent.ts, src/index.ts, src/shared/index.ts, src/shims-google-maps-d.ts, src/utils/index.ts, yarn.lock
=> feat: custom markers

README.md, docs/advanced-usage/index.md
* ready flag must be accessed with optional chaining,
* computed value markerIcon must be declared as const.
=> Corrections on advanced usage patterns

src/components/GoogleMap.vue, src/shared/index.ts
=> feat: allow loading api script externally

src/components/CustomMarker.vue, src/components/InfoWindow.vue
=> fix: dom managment conflicts in info windows and custom markers

src/components/HeatmapLayer.ts, src/components/InfoWindow.vue, src/components/index.ts
=> feat: heatmap layer

src/components/CustomMarker.vue
=> fix: expose custom marker

package.json, pnpm-lock.yaml, src/components/MarkerCluster.ts
=> feat(perf): new default clustering algo

src/utils/index.ts
=> fix: custom markers reactivity

docs/components/info-window.md, src/components/InfoWindow.vue
This would solve #143
Disclaimer: this has not been tested, so do not merge yet
=> Add vModel to infoWindow

src/shims-google-maps.ts, src/utils/index.ts
Reverts inocan-group/vue3-google-map#163
=> Revert "add fastDOM to batch DOM reads and writes"

docs/components/info-window.md, src/components/InfoWindow.vue
Reverts inocan-group/vue3-google-map#151
=> Revert "Add vModel to infoWindow"

package.json, vite.config.ts
=> fix: use with SSR

README.md, docs/advanced-usage/index.md, docs/getting-started/index.md
Added a small section mentioning the option to listen for map events on the GoogleMap component
=> Mention of listening to map events

src/components/GoogleMap.vue
Support https://github.com/inocan-group/vue3-google-map/issues/309
=> Support CameraControl

src/components/InfoWindow.vue
=> fix(InfoWindow): resolve timing issue with nested InfoWindow in markers
